# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=100)),
                ('distribution_list', models.EmailField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date sent')),
                ('in_reply_to', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('lists', models.ManyToManyField(to='luath_api.List')),
                ('references', models.ManyToManyField(related_name='_message_references_+', to='luath_api.Message')),
            ],
        ),
    ]
