# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luath_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='in_reply_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
