# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luath_api', '0002_auto_20161027_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
